name: Publish Production Image

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Read Version
        id: get_version
        run: |
          VERSION=$(cat VERSION | tr -d '\r\n[:space:]')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Calculate Image Tag
        id: get_tag
        run: |
          SHA7=$(echo "${{ github.sha }}" | cut -c1-7)
          TAG="${{ steps.get_version.outputs.version }}-$SHA7"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-1

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: payment-service
          IMAGE_TAG: ${{ steps.get_tag.outputs.tag }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
